app1/urls.py
from django.contrib import admin
from django.urls import path
from app1 import views

urlpatterns = [
    path('',views.home,name='home'),
    path('home.html',views.home,name="home.html"),
    path('contact.html',views.contact, name='contact'), 
    path('signup',views.signup, name='signup'),
    path('signin',views.signin, name='signin'),
    path('signout', views.signout, name='signout'),
    path('feedback/', views.feedback, name='feedback'),
    path('feedback/success/', views.feedback_success, name='feedback_success'),
   
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

app1/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

class Contact(models.Model):
    name = models.CharField(max_length=122)
    email = models.CharField(max_length=122)
    # phone = models.CharField(max_length=12)
    desc = models.TextField()
    # date = models.DateField()

    def __str__(self):
        return self.name

app1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Feedback

class Signupform(UserCreationForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email','password1','password2']        

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['name', 'email', 'message']

app1/views.py
from django.shortcuts import render,HttpResponse, redirect
from .forms import Signupform
from django.contrib.auth.forms import AuthenticationForm   # for signin view
from django.contrib.auth import authenticate, login, logout # for sign in
from .forms import FeedbackForm
from .models import Feedback
from app1.models import Contact
from django.contrib import messages


# Create your views here.
def home(reuqest):
    return render(reuqest,'home.html')


def signup(request):
    if request.method == "POST":
        fm = Signupform(request.POST)
        if fm.is_valid():
            fm.save()
            # messages.success(request, 'You have register successfully.')
            return redirect("signin")
    else:    
        fm=Signupform()
    return render(request,'Signup.html',{'fm':fm})
   
def signin(request):
    if request.method == "POST":
        fm = AuthenticationForm(request=request, data=request.POST)
        if fm.is_valid():
            uname = fm.cleaned_data['username']
            upass = fm.cleaned_data['password']
            user = authenticate(username=uname, password=upass)
            if user is not None:
                login(request, user)
                return render(request, 'home.html', {'user': user,})
    else:
        fm = AuthenticationForm()
    return render(request, "signin.html", {'user_data': fm})

def signout(request):
    logout(request)
    return redirect('/')

def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('feedback_success')
    else:
        form = FeedbackForm()
    return render(request, 'feedback.html', {'form': form})

def feedback_success(request):
    feedbacks = Feedback.objects.all().order_by('-created_at')
    return render(request, 'feedback_success.html', {'feedbacks': feedbacks})

from .models import Contact

def contact(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        # phone = request.POST.get('phone')
        desc = request.POST.get('desc')
        contact_instance = Contact(name=name, email=email, desc=desc)
        contact_instance.save()
        messages.success(request, 'Your message has been sent!')
    return render(request, 'contact.html')

 

templates/Signin.html
{% extends "base.html" %}
{% block title %}Signin{% endblock title %}
{%block body%}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header bg-primary text-white">
                    <h3 class="text-center">Sign In</h3>
                </div>
                <div class="card-body custom-card-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {{ user_data.as_p }}
                        <input type="submit" value="Sign In" class="btn btn-success btn-block">
                    </form>
                    <p class="mt-3 text-center">Don't have an account? <a href="{% url 'signup' %}">Register</a></p>
                </div>
            </div>
        </div>
    </div>
</div>  
{%endblock%}

templates/Signup.html
{% extends "base.html" %}
{% block title %}SignUp{% endblock title %}
{%block body%}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header bg-primary text-white">
                    <h3 class="text-center">Sign Up</h3>
                </div>
                <div class="card-body custom-card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ fm.username.label_tag }}
                            {{ fm.username }}
                            <div class="text-danger">{{ fm.username.errors }}</div>
                        </div>
                        <div class="form-group">
                            {{ fm.first_name.label_tag }}
                            {{ fm.first_name }}
                            <div class="text-danger">{{ fm.first_name.errors }}</div>
                        </div>
                        <div class="form-group">
                            {{ fm.last_name.label_tag }}
                            {{ fm.last_name }}
                            <div class="text-danger">{{ fm.last_name.errors }}</div>
                        </div>
                        <div class="form-group">
                            {{ fm.email.label_tag }}
                            {{ fm.email }}
                            <div class="text-danger">{{ fm.email.errors }}</div>
                        </div>
                        <div class="form-group">
                            {{ fm.password1.label_tag }}
                            {{ fm.password1 }}
                            <div class="text-danger">{{ fm.password1.errors }}</div>
                        </div>
                        <div class="form-group">
                            {{ fm.password2.label_tag }}
                            {{ fm.password2 }}
                            <div class="text-danger">{{ fm.password2.errors }}</div>
                        </div>
                        <button type="submit" class="btn btn-success btn-block">Register</button>
                    </form>
                    <br>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title> {%block title%}{%endblock title%} 3RiTechnologies </title>

     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <meta name="description" content="">
     <meta name="keywords" content="">
     <meta name="author" content="">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

     <link rel="stylesheet" href="/static/css/bootstrap.min.css">
     <link rel="stylesheet" href="/static/css/font-awesome.min.css">
     <link rel="stylesheet" href="/static/css/owl.carousel.css">
     <link rel="stylesheet" href="/static/css/owl.theme.default.min.css">

     <!-- MAIN CSS -->
     <link rel="stylesheet" href="/static/css/templatemo-style.css">

     <style>
          .custom-card-body {
              margin-top: 20px; /* Adjust the value as needed */
          }
      </style>      

</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

     <!-- PRE LOADER -->
     <section class="preloader">
          <div class="spinner">

               <span class="spinner-rotate"></span>
               
          </div>
     </section>


     <!-- MENU -->
     <section class="navbar custom-navbar navbar-fixed-top" role="navigation">
          <div class="container">

               <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                    </button>

                    <!-- lOGO TEXT HERE -->
                    <a href="#" class="navbar-brand">3RiTechnologies</a>
               </div>

               <!-- MENU LINKS -->
               <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-nav-first">
                         <li><a href="home.html#top" class="smoothScroll">Home</a></li>
                         <li><a href="home.html#about" class="smoothScroll">About</a></li>
                         <li><a href="home.html#courses" class="smoothScroll">Courses</a></li>
                         <li><a href="contact.html" class="smoothScroll">Contact</a></li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                         {% if request.user.is_authenticated %}
                         <li class="nav-item">
                           <a class="nav-link" href="/feedback">feedback</a></li>
                         </li>
                         <li class="nav-item">
                           <a class="nav-link" href="/signout">SignOut</a>
                         </li>
                         <li class="nav-item">
                           <a class="nav-link">Welcome {{user}} :)</a>
                         </li>     
                         {%else%}
                         <li class="nav-item">
                         <a class="nav-link" href="/signup">SignUp</a>
                         </li>
                         <li class="nav-item">
                         <a class="nav-link" href="/signin">Signin</a>
                         </li>
                   {%endif%}
                    </ul>
               </div>

          </div>
     </section>

     {% block body %}

     {% endblock body %}

      <!-- FOOTER -->
      <footer id="footer">
        <div class="container">
             <div class="row">

                  <div class="col-md-4 col-sm-6">
                       <div class="footer-info">
                            <div class="section-title">
                                 <h2>Headquarter</h2>
                            </div>
                            <address>
                                 <p> 405, Rainbow Plaza Wakad- Nashik Phata BRTS Road above McDonalds Pimple Saudagar, Rahatani, Pune, Maharashtra 411017</p>
                            </address>

                            <ul class="social-icon">
                                 <li><a href="#" class="fa fa-facebook-square" attr="facebook icon"></a></li>
                                 <li><a href="#" class="fa fa-twitter"></a></li>
                                 <li><a href="#" class="fa fa-instagram"></a></li>
                            </ul>

                            <div class="copyright-text"> 
                                 <p>3RI Technologies Pvt. Ltd.</p>
                                 
                                 <p>© 2023 All Rights Reserved</p>
                            </div>
                       </div>
                  </div>

                  <div class="col-md-4 col-sm-6">
                       <div class="footer-info">
                            <div class="section-title">
                                 <h2>Contact Info</h2>
                            </div>
                            <address>
                                 <p>+91 830 810 3366, +91 962 386 8215</p>
                                 <p><a href="mailto:youremail.co">enquiry@3riechnologies.com</a></p>
                            </address>

                            <div class="footer_menu">
                                 <h2>Quick Links</h2>
                                 <ul>
                                      <li><a href="#">Career</a></li>
                                      <li><a href="#">Investor</a></li>
                                      <li><a href="#">Terms & Conditions</a></li>
                                      <li><a href="#">Refund Policy</a></li>
                                 </ul>
                            </div>
                       </div>
                  </div>

                  <div class="col-md-4 col-sm-12">
                       <div class="footer-info newsletter-form">
                            <div class="section-title">
                                 <h2>Newsletter Signup</h2>
                            </div>
                            <div>
                                 <div class="form-group">
                                      <form action="#" method="get">
                                           <input type="email" class="form-control" placeholder="Enter your email" name="email" id="email" required="">
                                           <input type="submit" class="form-control" name="submit" id="form-submit" value="Send me">
                                      </form>
                                      <span><sup>*</sup> Please note - we do not spam your email.</span>
                                 </div>
                            </div>
                       </div>
                  </div>
                  
             </div>
        </div>
   </footer>


   <!-- SCRIPTS -->
   <script src="/static/js/jquery.js"></script>
   <script src="/static/js/bootstrap.min.js"></script>
   <script src="/static/js/owl.carousel.min.js"></script>
   <script src="/static/js/smoothscroll.js"></script>
   <script src="/static/js/custom.js"></script>

</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block title%}Contact{%endblock title%}

{% block body%} 

<div class="container">
    <div class="row">

         <div class="col-md-6 col-sm-12">
            <form id="contact-form" role="form" action="contact.html" method="post">
                   <div class="section-title">
                        <h2>Contact us <small>we love conversations. let us talk!</small></h2>
                   </div>
                   {% csrf_token %}
                   <div class="col-md-12 col-sm-12">
                        <input type="text" class="form-control" placeholder="Enter full name" name="name" required="">
         
                        <input type="email" class="form-control" placeholder="Enter email address" name="email" required="">

                        <textarea class="form-control" rows="6" placeholder="Tell us about your message" name="desc" required=""></textarea>
                   </div>

                   <div class="col-md-4 col-sm-12">
                        <input type="submit" class="form-control" name="send message" value="Send Message">
                   </div>

              </form>
         </div>

         <div class="col-md-6 col-sm-12">
              <div class="contact-image">
                   <img src="/static/images/contact-image.jpg" class="img-responsive" alt="Smiling Two Girls">
              </div>
         </div>

    </div>
</div>

{%endblock body%} 

templates/feedback.html
{% extends "base.html" %}

{% block title%}Home{%endblock title%}

{% block body%}
<!-- feedback.html -->

<div class="container mt-5">
    <h2>Feedback Form</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Name:</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="id_email">Email:</label>
            {{ form.email }}
        </div>
        <div class="form-group">
            <label for="id_message">Message:</label>
            {{ form.message }}
        </div>
        <button type="submit" class="btn btn-success">Submit Feedback</button>
    </form>
    <br>
</div>

{%endblock body%}

templates/feedback_success.html
{% extends "base.html" %}

{% block title%}Home{%endblock title%}

{% block body%}
<!-- feedback_success.html -->

<div class="container mt-5">
    <h2>Feedbacks</h2>
    <ul class="list-group">
        {% for feedback in feedbacks %}
                <div class="container">
                    <div class="item">
                        <div class="tst-image">
                             <img src="/static/images/user.png" class="img-responsive" alt="">
                        </div>
                        <div class="tst-author">
                             <h4>{{ feedback.name }}</h4>
                             <span>({{ feedback.created_at }})</span>
                        </div>
                        <p>{{ feedback.message }}</p>
                   </div>
                </div>
      
        {% endfor %}
    </ul>
</div>

{%endblock body%}